fix StandardDefinitions.scala scaladoc
```
Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_181).
Type in expressions for evaluation. Or try :help.

scala> class C { def m(x: => Int) = ??? }
defined class C

scala> import scala.reflect.runtime.universe._
import scala.reflect.runtime.universe._

scala> val m = typeOf[C].member(TermName("m")).asMethod
m: reflect.runtime.universe.MethodSymbol = method m

scala> m.params(0)(0).info
<console>:16: error: value params is not a member of reflect.runtime.universe.MethodSymbol
       m.params(0)(0).info
         ^

scala> m.paramLists(0)(0).info
res1: reflect.runtime.universe.Type = => Int

scala> showRaw(m.paramLists(0)(0).info)
res2: String = TypeRef(ThisType(scala), scala.<byname>, List(TypeRef(ThisType(scala), scala.Int, List())))
```

(cherry picked from commit 505cd860d65d945b040ee7d88a76ef2deb022e13)